# Generated by Django 5.2.9 on 2025-12-23 16:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_employee_alter_userprofile_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='movieBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=100)),
                ('showtime', models.CharField(max_length=100)),
                ('screenname', models.CharField(max_length=100)),
                ('dateandtime', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
