# Generated by Django 5.2.9 on 2025-12-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_moviebooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('course', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
